[tool.poetry]
name = "pyplussource"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
ttkthemes = "^3.2.0"
autopep8 = "^1.5.5"
pygments = "^2.8.0"
pylint = "^2.6.0"
html-linter = "^0.4.0"
json5 = "^0.9.5"
pygments-json = "^0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"