[run-system]
requires = ["poetry>=0.12"]
run-backend = "poetry.masonry.api"

[tool]
[tool.poetry]
authors = ["ZCG-coder z-c-ge@outlook.com"]
description = ""
name = "PyPlus"
version = "6.0.0-beta"
[tool.poetry.dependencies]
PyTouchBar = "^0.2.0"
art = "^5.1"
json5 = "^0.9.5"
py2app = "^0.23"
pygments = "^2.8.0"
python = "^3.8"
requests = "^2.25.1"
setuptools = "^54.1.2"
ttkthemes = "^3.2.0"
