[tool.poetry]
authors = ["ZCG-Coder <z-c-ge@outlook.com>"]
description = "The editor that edits"
name = "NWEdit"
version = "0.6-dev"
[tool.poetry.dependencies]
python = ">=3.10,<3.12"
CairoSVG = "^2.5.2"
art = "^5.7"
Pillow = "^9.2.0"
Pygments = "^2.12.0"
PyTouchBar = "^0.2.0"
Send2Trash = "^1.8.0"
ttkthemes = "^3.2.2"
pyobjc-core = { version = "^9.0", markers = "sys_platform == 'darwin'" }  # Have to keep a legacy version
pyobjc-framework-Cocoa = { version = "^9.0", markers = "sys_platform == 'darwin'" }
tkterminal = "^0.1.0"
tkhtmlview = "^0.1.1.post5"
mistune = "^2.0.4"
json5rw = "^0.2.2"
pyvips = "^2.2.1"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.5"
pytest = "^7.1.2"
isort = "^5.10.1"
coverage = "^6.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportPropertyTypeMismatch = false
reportGeneralTypeIssues = false

[tool.pytest.ini_options]
pythonpath = [
    ".", "src",
]