[tool.poetry]
name = "PyPlus"
version = "7.0.0"
description = "The PyPlus Editor"
authors = ["Andy Zhang <z-c-ge@outlook.com>"]

[tool.poetry.dependencies]
python = "^3.8"
art = "^5.4"
json5 = "^0.9.6"
ttkthemes = "^3.2.2"
Pygments = "^2.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
